version: '3'

services:
  postgres:
    image: postgres:14.2
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./src/main/resources/initial_data_generation.sql:/docker-entrypoint-initdb.d/init.sql