--
-- PostgreSQL database dump
--

-- Dumped from database version 14.2 (Debian 14.2-1.pgdg110+1)
-- Dumped by pg_dump version 14.2

-- Started on 2022-05-08 12:13:57 BST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3344 (class 1262 OID 16384)
-- Name: library-system-db; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "library-system-db" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.utf8';


ALTER DATABASE "library-system-db" OWNER TO postgres;

\connect -reuse-previous=on "dbname='library-system-db'"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 209 (class 1259 OID 16385)
-- Name: borrowed; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.borrowed (
    id integer NOT NULL,
    item_id integer NOT NULL
);


ALTER TABLE public.borrowed OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 16388)
-- Name: borrowed_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.borrowed ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.borrowed_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 16389)
-- Name: items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.items (
    id integer NOT NULL,
    available_count integer NOT NULL,
    description character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    on_loan integer NOT NULL,
    release_date timestamp without time zone NOT NULL,
    type character varying(255),
    image character varying(255)
);


ALTER TABLE public.items OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 16394)
-- Name: items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.items_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.items_id_seq OWNER TO postgres;

--
-- TOC entry 3345 (class 0 OID 0)
-- Dependencies: 212
-- Name: items_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.items_id_seq OWNED BY public.items.id;


--
-- TOC entry 216 (class 1259 OID 16410)
-- Name: requested; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.requested (
    id integer NOT NULL,
    item_name character varying(255) NOT NULL,
    item_type character varying(255) NOT NULL,
    request_reason character varying(255) NOT NULL
);


ALTER TABLE public.requested OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16409)
-- Name: requested_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.requested ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.requested_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 16395)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    email character varying(255) NOT NULL,
    enabled boolean,
    firstname character varying(255) NOT NULL,
    lastname character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 16400)
-- Name: user_accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_accounts_user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.user_accounts_user_id_seq OWNER TO postgres;

--
-- TOC entry 3346 (class 0 OID 0)
-- Dependencies: 214
-- Name: user_accounts_user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.user_accounts_user_id_seq OWNED BY public.users.user_id;


--
-- TOC entry 3182 (class 2604 OID 16401)
-- Name: items id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.items ALTER COLUMN id SET DEFAULT nextval('public.items_id_seq'::regclass);


--
-- TOC entry 3183 (class 2604 OID 16402)
-- Name: users user_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users ALTER COLUMN user_id SET DEFAULT nextval('public.user_accounts_user_id_seq'::regclass);


--
-- TOC entry 3331 (class 0 OID 16385)
-- Dependencies: 209
-- Data for Name: borrowed; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.borrowed (id, item_id) VALUES (1, 2);


--
-- TOC entry 3333 (class 0 OID 16389)
-- Dependencies: 211
-- Data for Name: items; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.items (id, available_count, description, name, on_loan, release_date, type, image) VALUES (3, 5, 'Power Rangers Macintosh game', 'Saban Power Rangers Zeo Versus The Machine Empire', 0, '2006-04-03 00:00:00', 'Video Game', 'power_ranger_image_1.jpeg');
INSERT INTO public.items (id, available_count, description, name, on_loan, release_date, type, image) VALUES (4, 1, 'Sleeping Beauty is the 1959 full length animated feature production from Walt Disney Studios', 'Sleeping Beauty', 0, '2000-02-02 00:00:00', 'Dvd', 'sleep_beauty_image_1.jpeg');
INSERT INTO public.items (id, available_count, description, name, on_loan, release_date, type, image) VALUES (1, 10, 'The Omnimatrix better known as the Omnitrix was a watch-like device that attached to Ben Tennyson wrist', 'Ben 10 classic omnitrix', 2, '2003-03-03 00:00:00', 'Toy', 'ben_tennyson_image_1.jpeg');
INSERT INTO public.items (id, available_count, description, name, on_loan, release_date, type, image) VALUES (2, 4, 'Jonathan Xavier Johnny Test is the main protagonist of the series of the same name', 'Johnny Test Comic', 2, '2004-03-04 00:00:00', 'Book', 'johnny_test_image_1.jpeg');


--
-- TOC entry 3338 (class 0 OID 16410)
-- Dependencies: 216
-- Data for Name: requested; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3335 (class 0 OID 16395)
-- Dependencies: 213
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.users (user_id, email, enabled, firstname, lastname, role, username) VALUES (1, 'disabled@library', false, 'Dexter', 'Lab', 'administrator', 'dexter.lab');
INSERT INTO public.users (user_id, email, enabled, firstname, lastname, role, username) VALUES (2, 'user@library.com', true, 'Ben', 'Tennyson', 'standard', 'ben.tennyson');


--
-- TOC entry 3347 (class 0 OID 0)
-- Dependencies: 210
-- Name: borrowed_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.borrowed_id_seq', 1, true);


--
-- TOC entry 3348 (class 0 OID 0)
-- Dependencies: 212
-- Name: items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.items_id_seq', 1, false);


--
-- TOC entry 3349 (class 0 OID 0)
-- Dependencies: 215
-- Name: requested_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.requested_id_seq', 1, false);


--
-- TOC entry 3350 (class 0 OID 0)
-- Dependencies: 214
-- Name: user_accounts_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_accounts_user_id_seq', 1, false);


--
-- TOC entry 3185 (class 2606 OID 16404)
-- Name: borrowed borrowed_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.borrowed
    ADD CONSTRAINT borrowed_pkey PRIMARY KEY (id);


--
-- TOC entry 3187 (class 2606 OID 16406)
-- Name: items items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_pkey PRIMARY KEY (id);


--
-- TOC entry 3191 (class 2606 OID 16416)
-- Name: requested requested_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.requested
    ADD CONSTRAINT requested_pkey PRIMARY KEY (id);


--
-- TOC entry 3189 (class 2606 OID 16408)
-- Name: users user_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT user_accounts_pkey PRIMARY KEY (user_id);


-- Completed on 2022-05-08 12:13:57 BST

--
-- PostgreSQL database dump complete
--

